language: erlang
otp_release:
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
script:
  - make dialyze
  - make tests

install:
  - URL='http://aphyr.com/riemann/riemann_0.2.6_all.deb'; FILE=`mktemp`; DEBIAN_FRONTEND=noninteractive; wget "$URL" -qO $FILE && sudo dpkg -i $FILE; rm $FILE
before_script:
  - sudo service riemann start
after_success:
  - make coverage-report
